//
//  ViewController.swift
//  Dicee
//
//  Created by Ricky Torrez on 1/22/19.
//  Copyright © 2019 E. Ricardo Torrez. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    // Array of dice images
    let diceArray = ["dice1","dice2","dice3","dice4","dice5","dice6"]
    
    // Variables to use as contianers for numbers generated by the roll button
    var randomDiceIndex1: Int = 0
    var randomDiceIndex2: Int = 0
    
    // Left dice roller
    @IBOutlet weak var diceImageView1: UIImageView!
    
    //Right dice roller
    @IBOutlet weak var diceImageView2: UIImageView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // On app load, roll the dice
        updateDiceImages()
    }

    // Roll button
    @IBAction func rollButtonPressed(_ sender: UIButton) {
        // Call on the updateDiceImages function to roll the dice
        updateDiceImages()
    }
    
    // Function that detects when the phone ends being shaken
    override func motionEnded(_ motion: UIEvent.EventSubtype, with event: UIEvent?) {
        
        // When the phone is shaken, roll the dice
        updateDiceImages()
    }


    func updateDiceImages() {

        // Create a random whole number (int) from 0 to 5 on dice index1
        randomDiceIndex1 = Int.random(in: 0 ... 5)
        
        // Create a random whole number (int) from 0 to 5 on dice index2
        randomDiceIndex2 = Int.random(in: 0 ... 5)
        
        // Sets the imageview on the left, we're setting it's image propery to equal UIImage that is named using the dice array and pick out a random member by using the random index
        // UIImage is a datatype
        diceImageView1.image = UIImage(named: diceArray[randomDiceIndex1])
        
        // Sets the imageview on the right, we're setting it's image propery to equal UIImage that is named using the dice array and pick out a random member by using the random index
        diceImageView2.image = UIImage(named: diceArray[randomDiceIndex2])
    }
}

